### ISSUE TITLE
n能够请教一下问题吗

### ISSUE THREAD

**Issue by james1kobby** [mapleFU/zookeeper_paper_cn#8]
你好，大佬，第一次看到这么优秀的文章，这篇文章解决了我在这一方面的很多疑惑(f分布式)，我想问问这一块有没有相关的代码能够推荐.

作为小白，很多东西都不理解，如果能够得到高人前辈指点一二，那就真的太感谢了！

非常感谢您能阅读这篇issues

**Comment by mapleFU** [comment]
这有什么能推荐的🤔直接看 MIT 6.824? 然后看看 ZooKeeper / Etcd ? 或者最简单的去看看 360 的 Raft？

还有这种问题总觉得和 issue 没啥关系，先 close 了. 如果有感兴趣的问题其实可以邮件联系的
